# config

# interval in mins
interval: 0.5

bbdc:
  username: "T0271643C"
  password: "711863"

chromedriver:
  host: http://localhost:4444

booking:
  want_sessions: ["1", "2", "3", "4", "5", "6", "7", "8"]

telegram:
  enabled: True
  token: "5252418627:AAHN4iEA3-CtHvOF9cn6q4CrQtbdFPdq4C8"
  chat_id: "-619908413"
